### ISSUE TITLE
Replace `dict` with user configurable data model 

### ISSUE THREAD

**Issue by Yun-Wu** [wildlife-dynamics/ecoscope-workflows#130]
ref: https://github.com/wildlife-dynamics/ecoscope-workflows/pull/123

**Comment by cisaacstern** [comment]
@Yun-Wu @walljcg @atmorling here is the proposal I shared for how I suggest we handle this


```python
from typing import Annotated

from pydantic import BaseModel, WithJsonSchema, TypeAdapter


class X(BaseModel):
    a: int
    b: str


def FrontendSchema(model: BaseModel):
    return WithJsonSchema(TypeAdapter(X).json_schema())


def g(x: Annotated[dict, FrontendSchema(X)]):
    return type(x), x


gjson = TypeAdapter(g).json_schema()
print(f"{gjson = }")

print(f"{g(x={'a': 1, 'b': '2'}) = }")
```

**Comment by cisaacstern** [comment]
Here is how this would look in a task signature: https://github.com/wildlife-dynamics/ecoscope-workflows/pull/135/files#r1704260220

**Comment by cisaacstern** [comment]
Based on discussion in https://github.com/wildlife-dynamics/ecoscope-workflows/pull/135/files#r1704309193 I can see the benefit of just using the schema directly as the type, let's proceed with that. Thanks @Yun-Wu.

**Comment by cisaacstern** [comment]
Note that this implicates registry task collection, see: https://github.com/wildlife-dynamics/ecoscope-workflows/pull/123#issuecomment-2269623179
