### ISSUE TITLE
Dashboard filters: enumNames is deprecated in RJSF

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#151]
Per @juanlescano-ng this is deprecated:

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/e596df3d66159e10f0f059a69b422c957cdf3a7b/ecoscope_workflows/jsonschema.py#L40

**Comment by whoisjuandev** [comment]
> enumNames is a non-standard JSON Schema field that was deprecated in version 5

Docs to support this deprecated property: https://rjsf-team.github.io/react-jsonschema-form/docs/migration-guides/v5.x%20upgrade%20guide/#non-standard-enumnames-property
