### ISSUE TITLE
Task groups for logical organization of configuration wizard

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#164]
Something like this: https://www.astronomer.io/docs/learn/task-groups

That allows us to programmatically represent what we are already doing with comments here:

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/98828f1662796eaad76c2f1925e38cc22579de0b/examples/compilation-specs/patrol_workflow.yaml#L3-L20

And that can included metadata such as a title + description for forthcoming UI requirements from @tiffanynwong.

Note that like Airflow Task Groups, these would be solely for UI intelligibility and not a logical/computational element.

**Comment by atmorling** [comment]
per offline discussion with @cisaacstern, we can represent these groups in JSON schema forms as nested objects

**Comment by cisaacstern** [comment]
implemented in #277
