### ISSUE TITLE
Additional required RJSF Filters ui fields for dashboard filters

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#178]
Per @juanlescano-ng, the following properties are required:

`ui:widget: "select"` <- if you want a select input
`ui:widget: "text"` <- if you want a text input
etc.

**Comment by whoisjuandev** [comment]
Let me add some documentation about the keys that you can use on this ui:widget property:

- [Documentation about Widgets on RJSF](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/widgets/)
