### ISSUE TITLE
Realistic data generators + example results data for patrols workflow

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#181]
Patrols workflow runs end-to-end but our example data is not especially visually compelling

xref #45 for a trajectories test data generator

Need to come up with a corresponding generator for events

Perhaps this implies changing the pattern of saving parquet samples directly to the repo

**Comment by walljcg** [comment]
Agreed. I've put together [this code](https://colab.research.google.com/drive/1DtI-Cz8c4t2Xkx1U1H7bCK5X9PB_ZNWj?usp=sharing) to generate synthetic relocations/trajectories data. Will need to think on how to contain within a given AOI. Or simply seed the initial points as some 2D Gaussian around a central point.

**Comment by walljcg** [comment]
Once we generate the fake relocations / events then we can use some form of [this notebook](https://colab.research.google.com/drive/1VEwGm5GEbCWHAjwuPtR5pJMCbYNhJobX?usp=sharing) to upload to ER

**Comment by walljcg** [comment]
@davidovichmarcos I made some updates and this seems to be working well to generate realistic synthetic tracks: https://colab.research.google.com/drive/1p3BOAMpJ0ewervvm1iSy_mzQeJWBocui?usp=sharing
