### ISSUE TITLE
Event Workflow

### ISSUE THREAD

**Issue by Yun-Wu** [wildlife-dynamics/ecoscope-workflows#191]
This task is to scope the tasks required for subject tracking workflow and will be split to smaller issues

**Comment by atmorling** [comment]
@Yun-Wu  I've opened the below tasks (and self-assigned) to track the additions needed for the workflow

- #192
- #193
- #194

Let me know if you think I've missed something

**Comment by Yun-Wu** [comment]
Thank you @atmorling for making it happen!

**Comment by walljcg** [comment]
- [ ] https://github.com/wildlife-dynamics/ecoscope-workflows/issues/281
