### ISSUE TITLE
Support grouping in EcoMap

### ISSUE THREAD

**Issue by Yun-Wu** [wildlife-dynamics/ecoscope-workflows#197]

**Comment by atmorling** [comment]
Does 'grouping' in this context meant a workflow/grouper level, or do we need to allow support for an actual `pandas.groupby` input?

**Comment by Yun-Wu** [comment]
Actual `pandas.groupby`. The global grouper will generate views. Here within a single view, the map can support different categories that may not be the same with the global grouper.

**Comment by atmorling** [comment]
Next question - is this specifically to allow categorical setting of things like `fill_color`? Or would you expect that each group would be an individual layer on the map? 
I can see both being useful, but the former is what we discussed the other day and is the immediate gap for the new workflows.

**Comment by Yun-Wu** [comment]
I have the former in mind and it should be enough for the subject tracking workflow. But I'm open to the second option too.
