### ISSUE TITLE
Map Task: title, base layer, etc

### ISSUE THREAD

**Issue by Yun-Wu** [wildlife-dynamics/ecoscope-workflows#232]
1. support multiple base layers
2. support opacity
3. support camera
4. north arrow sizing does not work??? Need to test again

**Comment by atmorling** [comment]
Would it be fair to say that this task is to improve the 'default' settings of the map within workflows?

**Comment by Yun-Wu** [comment]
No, I just removed the first title option since I realized it's already supported. But the rest will be added as extra features
