### ISSUE TITLE
Task: Get Patrol Tracks

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope-workflows#29]
Review Get Patrol Tracks Task. Look for ways to optimize speed within the underlying ecoscope ER_IO client call. Before / After validators should be able to serialize/deserialize to local Geoparquet and BigQuery  (using a DataConnection object).

Dependencies:
- [x] https://github.com/wildlife-dynamics/ecoscope-workflows/issues/32

**Comment by Yun-Wu** [comment]
Blocked by [#32](https://github.com/wildlife-dynamics/ecoscope-workflows/issues/32)

**Comment by Yun-Wu** [comment]
Duplicate with #42
