### ISSUE TITLE
Task: Filter Tracks

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope-workflows#30]
Before/After validators should support local geoparquet and bigquery in the cloud for now. 

Dependencies:

- [ ] https://github.com/wildlife-dynamics/ecoscope-workflows/issues/29

**Comment by Yun-Wu** [comment]
@walljcg @cisaacstern has added trajectory filters here: 

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/57e47cf88212c1435e7766779c3c5806197b23c2/ecoscope_workflows/tasks/preprocessing/_preprocessing.py#L64

Does it meet the requirements for this ticket?

**Comment by walljcg** [comment]
Yes, that function also does the filtering and makes sense to always have the two combined. In which case we probably don't need this as a separate task and can close this issue.
