### ISSUE TITLE
publish-to-prefix is broken and fails silently

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#320]
xref https://github.com/wildlife-dynamics/ecoscope-workflows/actions/runs/11358887750/job/31594157903#step:6:16

I can workaround for now by pushing these releases manually

**Comment by cisaacstern** [comment]
This was an expired key, which I fixed, but leaving this open so we can address the silent failure aspect

**Comment by atmorling** [comment]
This happened [again](https://github.com/wildlife-dynamics/ecoscope-workflows/actions/runs/11908373127/job/33183707442) 
I've updated to a key with a slightly longer shelf life
