### ISSUE TITLE
Bug: Subject tracking maps aren't showing data

### ISSUE THREAD

**Issue by atmorling** [wildlife-dynamics/ecoscope-workflows#392]
Assuming some styling params were lost in the RJSF Reckoning™

**Comment by atmorling** [comment]
This is because `AdvancedFields` are (rightfully) excluded from the `model_dump()` calls [here](https://github.com/wildlife-dynamics/ecoscope-workflows/blob/d30c0c2d35216f6a787dfcfeffbb97156da0876e/src/ecoscope-workflows-ext-ecoscope/ecoscope_workflows_ext_ecoscope/tasks/results/_ecomap.py#L283-L296)

**Comment by atmorling** [comment]
Had originally fixed this by adding a `model_dump_with_advanced` to the base style model, but realised that since `LayerStyle` is marked as `AdvancedField` in the task params, then maybe it's ok to have the layer style models not be marked as `AdvancedField`

**Comment by cisaacstern** [comment]
makes perfect sense!
