### ISSUE TITLE
Task: Get_Patrol_Relocations

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope-workflows#42]
We need a task to pull relocations from a patrol type from EarthRanger. This will be a very similar task to the [get_subjectgroup_observations()](https://github.com/wildlife-dynamics/ecoscope-workflows/blob/57e47cf88212c1435e7766779c3c5806197b23c2/ecoscope_workflows/tasks/io/_earthranger.py#L36) task.

**Comment by cisaacstern** [comment]
duplicate of #29, which is closed, so closing
