### ISSUE TITLE
In ecomap, zoom_to_bounds can sometimes zoom to levels without tiles

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#445]
In ecomap, we `zoom_to_bounds`

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/654d5f86b9e040b89a6b6e4be44afb762e3f8879/src/ecoscope-workflows-ext-ecoscope/ecoscope_workflows_ext_ecoscope/tasks/results/_ecomap.py#L319

however some tile layers, as defined like this

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/654d5f86b9e040b89a6b6e4be44afb762e3f8879/src/ecoscope-workflows-ext-ecoscope/ecoscope_workflows_ext_ecoscope/tasks/results/_ecomap.py#L90-L94

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/654d5f86b9e040b89a6b6e4be44afb762e3f8879/examples/events/spec.yaml#L78-L81

do not have tiles for very close-up view levels. In these cases, the default `zoom_to_bounds` is a map view without tiles. This can happen if, e.g., the events passed to the map are very small in number and/or tighly clustered to a very small geographic area.

I believe the fix for this might be to support, [at the ecoscope core lib layer, an option `max=` argument on `.zoom_to_bounds`](https://github.com/wildlife-dynamics/ecoscope/blob/7a06d57a3ce9b2b0ac27873ecd16a6959ffe3a86/ecoscope/mapping/map.py#L368-L396), which if given, is the maximum zoom level that `.zoom_to_bounds` will set, regardless of the features passed to it.\

Then here in workflows, we can call this like

```python
 @dataclass 
 class TileLayer: 
     name: str 
     opacity: float = 1 
     max: int = 1_000_000  #  a really high default (what is the actual max zoom level for map tiles?)

...

m.zoom_to_bounds(m.layers, max=(max([t.max for t in tile_layers]) if tile_layers else None))
```

**Comment by atmorling** [comment]
The [fix](https://github.com/wildlife-dynamics/ecoscope/pull/322) for the sub-issue adds support for the above `max_zoom` param, but _also_ adds a max zoom to the tile layers themselves such that we won't ever try fetch tiles past a max zoom level.

With that in place, the above change in workflows isn't technically necessary.
