### ISSUE TITLE
Add legend to feature density maps

### ISSUE THREAD

**Issue by atmorling** [wildlife-dynamics/ecoscope-workflows#459]
This needs some thought around the display values for the legend, the `density` column alone won't be very descriptive

**Comment by cisaacstern** [comment]
Based this blame

https://github.com/wildlife-dynamics/ecoscope-workflows/blame/4b0d970d0bc41691f703ca059049c3c4226ca1b9/examples/events/ecoscope-workflows-events-workflow/ecoscope_workflows_events_workflow/dags/jupytext.py#L436

which shows that line being added in #460, I assume perhaps your last recompile commit on #460 may have been against a local version of the spec that had some experimental inline defaults, i.e.

```yaml
    legend:
       label_column: "density",
       color_column": "density_colormap"
```

which were compiled against in #460 but not themselves committed?

I am trying to figure out why those params are here

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/4b0d970d0bc41691f703ca059049c3c4226ca1b9/examples/events/ecoscope-workflows-events-workflow/ecoscope_workflows_events_workflow/dags/jupytext.py#L429-L436

but not here

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/4b0d970d0bc41691f703ca059049c3c4226ca1b9/examples/events/spec.yaml#L147-L155

They are being dropped by the auto-recompiles in https://github.com/wildlife-dynamics/ecoscope-workflows/pull/452, and just want to make sure that's not a mistake. I think I'm convinced its not.

**Comment by cisaacstern** [comment]
Put another way, is the above a case of us not having this ci check https://github.com/wildlife-dynamics/ecoscope-workflows/issues/430?issue=wildlife-dynamics%7Cecoscope-workflows%7C433 ?

**Comment by atmorling** [comment]
Yep, that's 100% what happened 😅
