### ISSUE TITLE
Workflows pixi.toml's are imcompatible with pixi 0.39.0

### ISSUE THREAD

**Issue by atmorling** [wildlife-dynamics/ecoscope-workflows#514]
See [here](https://github.com/wildlife-dynamics/ecoscope-workflows/actions/runs/12130520362/job/33821022484) for an example

It's unclear if this is an intended change from pixi or not, however this diff works for the parent pxi.toml:
```diff
- [feature.compile.dependencies.ecoscope-workflows-core]
- version = "*"
- channel = "file:///tmp/ecoscope-workflows/release/artifacts/"

- [feature.compile.dependencies.ecoscope-workflows-ext-ecoscope]
- version = "*"
- channel = "file:///tmp/ecoscope-workflows/release/artifacts/"

+ [feature.compile.dependencies]
+ ecoscope-workflows-core = {version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/"}
+ ecoscope-workflows-ext-ecoscope = {version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/"}
```

Also noting that in compiler.py we have:
https://github.com/wildlife-dynamics/ecoscope-workflows/blob/49736797f771a27fbe683291624db6818e4fda00/src/ecoscope-workflows-core/ecoscope_workflows_core/compiler.py#L825-L832

But the generated toml file looks like this:
https://github.com/wildlife-dynamics/ecoscope-workflows/blob/49736797f771a27fbe683291624db6818e4fda00/examples/events/ecoscope-workflows-events-workflow/pixi.toml#L19-L45

**Comment by atmorling** [comment]
I've experimented with getting tomli_w to spit out the 'expected' structure here - seems like it's actually not possible based on stylistic choices it's making.

Might need to pin our CI to pixi==0.38.0 in the meantime.

**Comment by cisaacstern** [comment]
I've opened https://github.com/prefix-dev/pixi/issues/2640 to track upstream
