### ISSUE TITLE
Task: Define Groupers

### ISSUE THREAD

**Issue by Yun-Wu** [wildlife-dynamics/ecoscope-workflows#72]
Define groupers

https://lucid.app/lucidchart/648e2fe6-0416-4688-912c-d44f14297372/edit?invitationId=inv_83b12d9a-57da-4ce0-b28f-c5957b4303b3&referringApp=slack&page=0_0#

**Comment by cisaacstern** [comment]
Momentarily blocked by:

- [ ] On get-params, duplicate arg names between tasks can result in unintended omissions

**Comment by cisaacstern** [comment]
closed by #162
