### ISSUE TITLE
Task: Create EcoMap with multiple GDFs (e.g., Tracks & Events)

### ISSUE THREAD

**Issue by Yun-Wu** [wildlife-dynamics/ecoscope-workflows#78]
This task may be trivial after the merged dataframes. Need to check with @atmorling

**Comment by atmorling** [comment]
The gap here is the EcoMap task not handling mixed geometry dataframes, currently one has to explicitly define the geometry type for visualisation. 

Per my comments on #64, we probably want to separate creating map layers out into it's own task, and the `draw_ecomap` task would take a set of layers, not dataframes, as input
