### ISSUE TITLE
Review task params against standard REACT JSON Schema forms

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope-workflows#93]
Review all the task params within the patrols workflow and compare against the 'out-of-the-box' (shot-cn) json schema controls to see what we might need to customize ourselves versus what we get for free (e.g.,  floats, text, arrays, tuples, dicts, datetime, integers, )

**Comment by cisaacstern** [comment]
xref https://github.com/wildlife-dynamics/ecoscope-workflows/issues/82#issuecomment-2240880664

**Comment by Yun-Wu** [comment]
Here are the issues identified during research:

- `dict` is not supported by react-jsonschema-form. While we could represent it as an array of key-value pairs, our parser has to understand the key-value types, while dictionary values can be `Any`. `style_kws` is a good example where lonboard supports arguments of any types but we need to parse user input first to extract values of the correct type. My recommendation is to only support a subset of arguments which we specify the types, like what we did [here](https://github.com/wildlife-dynamics/ecoscope-modules/blob/main/ecoscope_modules/configs/module_configs/map_config.py). Happy to hear your thoughts: @walljcg @cisaacstern 
- `tuple` is not supported either, (used by `Filter`). Any reason we didn't make it a pydantic data model?
- `get_params_jsonschema` returns a dict of json schemas while react-jsonschema-form requires fields like `properties`. Added those fields in the dictionary.
- Added default values for some tasks.
- Task ID is not user-friendly in the forms. Use task names instead.
- More restrictions need to be applied in `patrol_workflow`
  - Filter point coordinates: like this: [[180, 90], [0, 0]]
- Other things that could be polished
  - Hide items with defaults
  - Nullable fields like `filename`, `view`, `groupers`
 
The fix can be found here #123

**Comment by cisaacstern** [comment]
Responses to above points in https://github.com/wildlife-dynamics/ecoscope-workflows/pull/123#pullrequestreview-2216061317 (responded on the PR to combine that with my review there)

**Comment by Yun-Wu** [comment]
Created the following tasks based on our discussion

- #130 
- #131 
- #132 
- #133 
- #134 

Hopefully this week I can get all patrol-workflow configuration correctly rendered (stretch goal). Then I'll work on key improvement for user experience.
